### PR TITLE
Add packagegroups for support ISP, AI/ML packages, and opencv i.MX fork packages.

### PR DESCRIPTION
**Pull request by chrisdimich**

### CODE REVIEW

**Comment by chrisdimich** [comment]
Just a gentle reminder. Can this be reviewed and merged?

**Review by otavio — CHANGES_REQUESTED** [review]
I think we could have some of this inside `meta-freescale-ml` itself. We did this for mfgtool for example as https://github.com/Freescale/meta-freescale/blob/master/recipes-fsl/packagegroups/packagegroup-fsl-mfgtool.bb

For things where `meta-freescale-ml` don't depend on other layers, we can leave it there.

**Comment by chrisdimich** [comment]
Okay fair enough. Do you want all packagegroups moved to meta-freescale or just packagegroup-fsl-ml?

**Comment by otavio** [comment]
I think the ml one belongs to ml layer.

**Comment by chrisdimich** [comment]
and the others move to meta-freescale?

**Comment by otavio** [comment]
Yes; I think it makes sense.

**Comment by chrisdimich** [comment]
Alright will do!

**Pull request closed without merging**
