### PR TITLE
imx-gpu-sdk: fix gcc10 build

### PR DESCRIPTION
**Pull request by zandrey**
GCC 10 dropped implicit inclusion of <stdexcept> [1], causing the
GPU SDK build to fail.

Introduce a patch which explicitly includes <stdexcept> at the base
header, effectively solving missing declarations in various SDK parts.

[1]: https://gcc.gnu.org/gcc-10/porting_to.html

Signed-off-by: Andrey Zhizhikin <andrey.z@gmail.com>

### CODE REVIEW

**Comment by zandrey** [comment]
@thochstein This patch should be reported to upstream, can you please take care of this?

Thanks a lot!

-- andrey

**Comment by thochstein** [comment]
Will do.

**Comment by ReneThrane** [comment]
Hi, thanks for pointing out the issue.  As a general rule we dont accept any patches on this repo as the official releases of the demo framework exist at https://github.com/NXPmicro/gtec-demo-framework. We also very carefully manage the versions so any patches would first be going into the internal release branch and then it becomes part of the next official release.

While this patch probably solves the issue, it itself is a issue as it would increase the build time for everything and introduce access to types that the user of the patched header file didnt ask for.
The framework has been carefully crafted to only include whats needed, so a properly crafted patch will only include the header were its actually needed. This is done because including too much causes major build time issues in C++ so we are very careful about what we include.

We do build the framework with the latest ubuntu releases and often have a canary build for the latest upcoming ubuntu release you did happen to catch us at a time where 20.04 was just released and we didnt not have time to upgrade the canary build to 20.10. I also do not know if 20.10 has gcc 10 yet. 

Anyways I will look into it and make sure that 5.6+ will have a fix in it.  I will also evaluate if the fix can be done for the upcoming 5.5.3 branch. Normally we dont go back and add such new compilers to a old build we officially only support building with ubuntu 18.04  and its included compiler and the gcc version included with the yocto bsp releases.

**Comment by ReneThrane** [comment]
This [document](https://github.com/NXPmicro/gtec-demo-framework/blob/master/CONTRIBUTING.md) describes our current contribute process. 

But this indicate we need a section that talks about how to handle include files in the framework.

Thanks again for submitting the issue.

**Comment by otavio** [comment]
@ReneThrane we appreciate your feedback, however, please consider using a more updated build environment for this kind of validation as LTS releases often are left behind on the toolchain tools.

As Yocto Project does make use of up to date toolchains, maybe you could consider using a custom Yocto Project toolchain for this validation work? if so, this reduces the risk of this breakage in future.

**Comment by ReneThrane** [comment]
Well we dont rely on LTS for validation but we do tend to use the latest ubuntu preview build for the canary builds for the **ubuntu build support** (which makes sense since we are building under ubuntu). Now historically the NXP yocto BSP releases have been using a older version of GCC than whats been included in the latest ubuntu image, so there has been no need to have another canary for upcoming GCC versions.  

Furthermore we build with the latest visual studio, the latest clang, the latest android sdk+ndk and we have many other combinations of older GCC and clang versions. So normally the demo framework has seen more different compilers than most of the other code which tend to make it fairly resilient  when exposed to new compilers. This is also shown by the history of issues we had with compilers since the initial version was released. Since 2014 we had one compiler issue that occurred in a third party library that didn't support the given GCC version (so technically not in our code) and this one..  So one compiler issue in six years for a pretty big code base seems like very little.

**Comment by ReneThrane** [comment]
Just for context:

GCC 10.1 
Released: May 7, 2020

Demo framework 5.5.x
Released: feb 2, 2020

So its not exactly weird that our release has never been compiled with a compiler that was released over three months after it.

**Comment by otavio** [comment]
@thochstein is NXP updating it?

@ReneThrane it is fairly normal. What I said is we could avoid new issues in the future if we are testing we newer releases and more important, if you review patches which fix issues. Only this.

**Comment by zandrey** [comment]
> 
> 
> Hi, thanks for pointing out the issue.

No problem!

> As a general rule we dont accept any patches on this repo as the official releases of the demo framework exist at https://github.com/NXPmicro/gtec-demo-framework. We also very carefully manage the versions so any patches would first be going into the internal release branch and then it becomes part of the next official release.

This is understandable, and I consider it a good practice. However, now we're looking at the hot-fix, which should be integrated into current public releases. Without this **logical** fix then entire SDK build is broken and cannot be used with the `master` branch of Yocto.

> 
> While this patch probably solves the issue, it itself is a issue as it would increase the build time for everything and introduce access to types that the user of the patched header file didnt ask for.

On the other hand (if we talk honest): relying on implicit inclusion of the header - is also not all that great. This is what happened, and with the GCC update it hit the component back... This might even went unnoticed during development, but now when the latest version of the toolchain reports this - it should be considered, IMHO.

> The framework has been carefully crafted to only include whats needed, so a properly crafted patch will only include the header were its actually needed. This is done because including too much causes major build time issues in C++ so we are very careful about what we include.

I also tend to do exactly the same in my projects, and if something gets broken along the way - I get to fix it.

> 
> We do build the framework with the latest ubuntu releases and often have a canary build for the latest upcoming ubuntu release. But you did happen to catch us at a time where 20.04 was just released and we did not have time to upgrade the canary build to 20.10. I also do not know if 20.10 has gcc 10 yet.

I was actually in the process of upgrading the `5.0.2` to `5.4.0` when I caught this issue. I've compiled the `5.4.0` first, and when it turned out that it is affected - I tried to compile the current SDK version. When I realized that both versions exhibit the same issue, my strategy was to patch the current one, report it upstream and get the status on the issue - which we all eventually got here from you! 😉 

> 
> Anyways I will look into it and make sure that 5.6+ will have a fix in it. I will also evaluate if the fix can be done for the upcoming 5.5.3 branch.

I really appreciated your feedback here regarding the prospective release state for this issue. I believe NXP and @otavio should monitor this information and decide which version of SDK should be kept on `dunfell` and which should be taken into `master` further.

> Normally we dont go back and add such new compilers to a old build we officially only support building with ubuntu 18.04 and its included compiler and the gcc version included with the yocto bsp releases.

This is the beauty of Yocto Project - you get all the latest tools (GCC in one of them) so you get to identify all your potential problems really fast and ahead of time before it gets into the Host OS.

Please take this patch as an indication of the issue that does exists in the code and should be addressed, otherwise with (maybe) Ubuntu 20.10 we would all be having the same review. 😃 

-- andrey

**Comment by zandrey** [comment]
> 
> 
> Just for context:
> 
> GCC 10.1
> Released: May 7, 2020
> 
> Demo framework 5.5.x
> Released: feb 2, 2020
> 
> So its not exactly weird that our release has never been compiled with a compiler that was released over three months after it.
> 
> Also it appears to be 5.0.2 that is in this repo
> Released: Feb 26, 2018
> 
> So the issue is with a compiler that came out over two years after this release.

Just for the record: 😄 
As I indicated above the issue is not with the compiler. The issue came from implicit inclusion of certain headers, which has been addressed with version 10 of GCC.

From [GCC 10 Porting Guide](https://gcc.gnu.org/gcc-10/porting_to.html):
```
C++ language issues
Header dependency changes

Some C++ Standard Library headers have been changed to no longer include the <stdexcept> header. As such, C++ programs that used components defined in <stdexcept> or <string> without explicitly including the right headers will no longer compile.

Previously components such as std::runtime_error, std::string and std::allocator were implicitly defined after including unrelated headers such as <array> and <optional>. Correct code should include the appropriate headers for the classes being used. 
```

**Comment by ReneThrane** [comment]
> @ReneThrane it is fairly normal. What I said is we could avoid new issues in the future if we are testing we newer releases and more important, if you review patches which fix issues. Only this.

@otavio to expect a two year old release to work with a just released compiler that changed things will never be something we can prevent.. The build worked with all available compilers at the time of the release. There is not much we can do better.

I currently scheduled a check for the current release of the demo framework which is 5.5.2 and the upcoming 5.6 and if any issues are found they ought to be fixed..   My preliminary testing of a few apps showed no issues so far.. But I did not have time to do a full build its late evening here.

**Comment by ReneThrane** [comment]
> Just for the record: 😄
> As I indicated above the issue is not with the compiler. The issue came from implicit inclusion of certain headers, which has been addressed with version 10 of GCC.

I am fully aware its not technically a GCC 10 issue. But given the issue does not appear in 5.5.2 or the upcoming 5.6 release on previous GCC versions nor any of the other versions its fair to say that the issue is caused by a change in GCC 10.. You can technically argue that its a error in the code that it doesn't include all possible header files it needs but when said code compiles without errors on multiple different compilers and have done so for years, then it can also be argued that the 'cause' of the problem is the changes in GCC 10 since its naieve to expect people to manually verify that all code include everything they need as that's what a compiler is for and if GCC, clang and MSVC incorrectly include the needed header file in earlier versions then its natural to expect this 'bug' to propagate into all code that relies on the those compilers..

**Comment by zandrey** [comment]
> 
> 
> > Just for the record: 😄
> > As I indicated above the issue is not with the compiler. The issue came from implicit inclusion of certain headers, which has been addressed with version 10 of GCC.
> 
> @zandrey
> I am fully aware its not technically a GCC 10 issue. But given the issue does not appear in 5.5.2 or the upcoming 5.6 release on previous GCC versions nor any of the other versions its fair to say that the issue is caused by a change in GCC 10..

@ReneThrane 
Please do not get me wrong: I'm not trying to classify this issue to be either code- or toolchain-related. All I said is that a combination of latest GCC 10 release and GPU SDK source has a compilation issue which should be addressed.

> You can technically argue that its a error in the code that it doesn't include all possible header files it needs but when said code compiles without errors on multiple different compilers and have done so for years, then it can also be argued that the 'cause' of the problem is the changes in GCC 10 since its naieve to expect people to manually verify that all code include everything they need as that's what a compiler is for and if GCC, clang and MSVC incorrectly include the needed header file in earlier versions then its natural to expect this 'bug' to propagate into all code that relies on those compilers..

IMHO, that is totally fine! You can think about it like you've received a *"sneak pick"* of what would be streamlined in the future (toolchains would eventually be updated on Host Distros; Fedora 32 is shipped with GCC 10 per default), and you have a chance to react early enough, thus making your component error-prone and ready for the future.

This is what Yocto provides here, and this is actually how I personally treat it in my work. 😉 

Cheers!
-- andrey

**Comment by ReneThrane** [comment]
@zandrey 

I am very happy to get notified about possible issues with our code and future tool chains however I can not promise that we will fix it for a old release even if its current (that will have to be a company decision).  At the time we do a release our current canary system has proven effective in catching possible issues well before we do a release that might use those tool chains.

I will however ask our test team if we can get a special canary yocto build that uses the latest compiler versions to improve our coverage.

**Comment by ReneThrane** [comment]
As the main maintainer of the demo framework I would really recommend you undo this change and instead apply the fix in the few places where its missing. This will match any upstream fixes we do.

**Pull request merged**
