### PR TITLE
Update weston-init.bbappend

### PR DESCRIPTION
**Pull request by mauzil**
I see this error in hardknott

### CODE REVIEW

**Comment by thochstein** [comment]
Hi @mauzil, did you actually encounter a problem? The override character is in fact changing from `_` to `:`. The new character is valid for `hardknott`, though not required until `honister`.

**Comment by mauzil** [comment]
I'm working in hardknott and bitbake give me error on weston-init.bbappend for the ':' in place of '_'
Sorry if I changed in the wrong branch

**Comment by thochstein** [comment]
Okay, I'm building now. It's past the parse stage. Was the error after the parse?

**Comment by mauzil** [comment]
I move to branch hardknott restore the ':' in place of '_'
I try the build with bibtake and I get this error
ERROR: ParseError at /home/yocto/hardknott/sources/meta-freescale-distro/recipes-graphics/wayland/weston-init.bbappend:1: unparsed line: 'FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"'

**Comment by otavio** [comment]
Are you using an outdated hardknott branch?

**Comment by mauzil** [comment]
I pull from https://github.com/Freescale/meta-freescale-distro, then checkout on hardknott

**Comment by otavio** [comment]
Sure; but I meant OE-Core/Poky.

**Comment by mauzil** [comment]
I check every layer and they are in hardknott branch

<table>
<tr><td>poky</td><td>origin/hardknott</td></tr>
<tr><td>base</td><td>origin/hardknott</td></tr>
<tr><td>meta-freescale</td><td>origin/hardknott</td></tr>
<tr><td>meta-freescale-3rdparty</td><td>origin/hardknott</td></tr>
<tr><td>meta-freescale-distro</td><td>origin/hardknott</td></tr>
<tr><td>meta-openembedded</td><td>origin/hardknott</td></tr>
</table>

**Comment by thochstein** [comment]
You're not using `repo init/repo sync`, as shown in the [README](https://github.com/Freescale/fsl-community-bsp-platform/blob/hardknott/README.adoc)? Can you check the log for poky to see that it is up to date?

**Comment by mauzil** [comment]
Ok, I found the **my** mistake.
The poky layer was not updated even if I made a checkout on the latest hardknott tag.
I compared the bitbake source and in the last poky hardknott the ':' is added as separator 

Please forget my patch :-(

**Comment by otavio** [comment]
Good you found it. I'm closing it now.

**Pull request closed without merging**
