### PR TITLE
Upgrade imx-gpu-sdk to 5.6.1, aligned with NXP 5.4.47-2.2.0

### PR DESCRIPTION
**Pull request by thochstein**
Requires https://github.com/Freescale/meta-freescale/pull/532.

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by zandrey** [comment]
@thochstein 

I've picked up this PR as patch series and applied on top of master here. With that, the build is failing with following errors:

```
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-fsl-tools-gpu-1.0-r0.imx8mpevk requires imx-gpu-sdk, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides gli needed by imx-gpu-sdk-5.6.1-r0.cortexa53-crypto-mx8mp
 * 
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-fsl-tools-gpu

```

It looks like there is a missing dependency to `gli` that is introduced with this PR.

Can you take a look at which recipe provides it in your setup?

-- andrey

**Comment by thochstein** [comment]
Thanks, @zandrey, I forgot some updates.

**Comment by zandrey** [comment]
@thochstein This update apples and builds OK, thanks for taking care of this!

Is it correct that in order to proceed with this PR and [Freescale/meta-freescale#532](https://github.com/Freescale/meta-freescale/pull/532) - it is still required that [mesa patch in OE-Core](https://lists.openembedded.org/g/openembedded-core/message/144536) is merged before?

-- andrey

**Comment by otavio** [comment]
> @thochstein This update apples and builds OK, thanks for taking care of this!
> 
> Is it correct that in order to proceed with this PR and [Freescale/meta-freescale#532](https://github.com/Freescale/meta-freescale/pull/532) - it is still required that [mesa patch in OE-Core](https://lists.openembedded.org/g/openembedded-core/message/144536) is merged before?

We could add the patch on meta-freescale and once it is merged we remove it.

**Comment by zandrey** [comment]
> 
> 
> > @thochstein This update apples and builds OK, thanks for taking care of this!
> > Is it correct that in order to proceed with this PR and [Freescale/meta-freescale#532](https://github.com/Freescale/meta-freescale/pull/532) - it is still required that [mesa patch in OE-Core](https://lists.openembedded.org/g/openembedded-core/message/144536) is merged before?
> 
> We could add the patch on meta-freescale and once it is merged we remove it.

I did think about this yesterday, but could not come up with a clear solution on how to track the upstream integration status.

My guess: if the patch is taken now in `meta-freescale` and then once applied in upstream - build would fail with duplicated patch error for `mesa`. If that is acceptable - then I believe this can be done.

-- andrey

**Comment by otavio** [comment]
Yes, it'll happen and then we drop the patch. To make it easier, we can put the patch as a specific commit which we can revert once it is merged there.

**Comment by thochstein** [comment]
Okay, I added the mesa patch to https://github.com/Freescale/meta-freescale/pull/532.

**Comment by zandrey** [comment]
@thochstein @otavio:
This PR, combined with updated [Freescale/meta-freescale#532](https://github.com/Freescale/meta-freescale/pull/532), builds fine for `imx8mmevk`, `imx8mpevk` and `imx7dsabresd` machines.

-- andrey

**Comment by otavio** [comment]
@thochstein have you tested the imx6qdlsabresd?

**Comment by thochstein** [comment]
I haven't tried since a few weeks ago. At the time uboot-imx was not building, and using uboot-fslc I was not getting out of boot.

**Comment by thochstein** [comment]
Actually, I guess I did just build `fsl-image-machine-test` with `u-boot-imx`. I'll give it a try.

**Comment by thochstein** [comment]
Note, `poky` did just take the `mesa` patch.

**Pull request merged**
