### PR TITLE
weston-init: change to weston user

### PR DESCRIPTION
**Pull request by liuming50**
Now weston is being started as weston user, adapt to that.

Signed-off-by: Ming Liu <liu.ming50@gmail.com>

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by thochstein** [comment]
This is not correct. XDG_RUNTIME_DIR is a user variable, not a weston variable. We talked about this here: https://github.com/Freescale/meta-freescale-distro/pull/86#issuecomment-1054330038

**Comment by otavio** [comment]
My bad. I will revert it.

@liuming50 are you fixing a issue or just rework?

**Comment by liuming50** [comment]
> My bad. I will revert it.
> 
> @liuming50 are you fixing a issue or just rework?

Hi, @otavio I was fixing a issue, without this change, I could not start a weston terminal when after logging in by serial console or ssh.

From my point of view, https://source.codeaurora.org/external/imx/meta-imx/commit/?id=3519f6bb seems not a proper fix or even not a complete workaround, because it only touches weston.service, but there are a few other "weston user" being referred in weston-start/weston.socket and so on.

**Comment by otavio** [comment]
Did you have  a look one @thochstein comment above? please check the discussion he referred to.

**Comment by liuming50** [comment]
> Did you have a look one @thochstein comment above? please check the discussion he referred to.

Yes, I have read that, if I understand correctly, the major concern of @thochstein is this change breaks the spec of XDG_RUNTIME_DIR, which I am on board, but this fix https://source.codeaurora.org/external/imx/meta-imx/commit/?id=3519f6bb is also incomplete and confusing (multiple users root/weston in different places), so I made this: https://github.com/Freescale/meta-freescale-distro/pull/90, maybe that could be a solution for this issue? That fix my issue per test, running weston-terminal by root user through ssh login.

@otavio

**Comment by gibsson** [comment]
The problem is that the doc says XDG_RUNTIME_DIR should match the user id you're in. So setting it to the weston id goes against the doc. That is why pam_systemd does what it does. Also in my case, due to pam_systemd, XDG_RUNTIME was already set, so this profile change is actually useless as long as we test if the variable exists or not.

**Comment by liuming50** [comment]
> The problem is that the doc says XDG_RUNTIME_DIR should match the user id you're in. So setting it to the weston id goes against the doc. That is why pam_systemd does what it does. Also in my case, due to pam_systemd, XDG_RUNTIME was already set, so this profile change is actually useless as long as we test if the variable exists or not.

Thanks for the explanation, how do you think this PR: https://github.com/Freescale/meta-freescale-distro/pull/90, if we change to use WAYLAND_DISPLAY, that also fixes my problem.

**Pull request merged**
