### PR TITLE
Upgrade imx-gpu-sdk, fix NXP distro

### PR DESCRIPTION
**Pull request by thochstein**
- Upgrade imx-gpu-sdk to 5.5.3, fixing the build
- Add recipes for imx-gpu-sdk dependencies
- Fix NXP distro for 8QXP and 8QM

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by zandrey** [comment]
@thochstein I see that with this upgrade, the build of Vulkan demos is failing because it is missing `glslangValidator`.

```
ERROR: Could not locate the content builder 'glslangValidator' (Vulkan shader compiler used to convert GLSL/HLSL shaders to binary SPIR-V files)
```

This is detailed in the [GPU SDK Yocto Setup Guide](https://github.com/NXPmicro/gtec-demo-framework/blob/81da0a88e8310181814d88be4a2513220d487ca2/Doc/Setup_guide_yocto.md), but the native dependency is not present anywhere in the layer.

I used _imx8mnevk_ machine to build this package, as it should have a support for Vulkan (according to `FEATURES_SOC` settings in the recipe).

I guess this should be addressed further, or `Vulkan` should be dropped from `FEATURES_SOC` as it is unbuildable.

-- andrey

**Comment by thochstein** [comment]
Hmm, I think this worked for me because I was originally working with a `vulkan-validationlayers` recipe, which depended on a `glslang` recipe that we have locally. I was having troubles with the `vulkan-validationlayers` recipe and switched the dependency in the SDK to `vulkan-loader` since `vulkan-validationlayers` is just a development wrapper. After doing a `cleansstate` I see the same error. Let me see if I can fix this with our `glslang` recipe.

**Comment by thochstein** [comment]
@zandrey, fixed here: https://github.com/Freescale/meta-freescale-distro/pull/37

**Comment by zandrey** [comment]
> @zandrey, fixed here: #37

@thochstein Thanks a lot!

_imx8mnevk_ build went fine, Vulkan demos can be compiled. 👍

**Pull request merged**
